### ISSUE TITLE
Un singur repository pentru toate subiectele meta

### ISSUE THREAD

**Issue by randunel** [gov-ithub/guidelines#1]
Repo „code-review” implică repo separat pentru „contribution guidelines” sau orice pentru altceva. Nu ar fi mai bun un singur repository pentru tot ce poate fi considerat metadata?

Am detaliat propunerea într-un gist https://gist.github.com/randunel/391c01d9cf82529eedb8cc0883e82a2f

**Comment by mess110** [comment]
+1

@rusanu poți să redenumești proiectul in "guidelines"?

**Comment by rusanu** [comment]
'guidelines' it is
