### ISSUE TITLE
Tehnologii acceptate

### ISSUE THREAD

**Issue by gpgabriel** [gov-ithub/guidelines#11]
Consider ca este gresit sa stabilim o lista de tehnologii acceptate. Tehnologiile ar trebui stabilite in functie de nevoile proiectelor. Propun sa stergem aceasta categorie din repository.

**Comment by cezarneaga** [comment]
si eu sunt de aceeasi parere dar ar fi fain sa mai fie si alte pareri. daca mai sunt oameni de aceeasi parere @gpgabriel fa un pull request :)
