### ISSUE TITLE
Chiar avem nevoie de guidelines atat de restrictive pe db?

### ISSUE THREAD

**Issue by ClaudiuCeia** [gov-ithub/guidelines#13]
Mi se pare cam project specific ce avem la database, cel putin partea asta: https://github.com/gov-ithub/guidelines/blob/master/databases/Db_Standards_CamelCase.md

Si ca idee, numele tabelelor si al coloanelor ar trebui sa fie atat de departe de codul de care te lovesti in mod regulat ca nu ar prea trebui sa conteze. Singura data cand te lovesti de un nivel asa de jos ar fi undeva in framework-ul de model, si mai mult de atat, cred ca si acolo nu vorbim decat de cod _declarativ_ nu _imperativ_.

Dar bine, acum depinde, mai sunt si framework-uri din-astea open source care-s prost gandite si au tight coupling intre nume de clase si tabele din baza de date and what not, dar hai sa nu le luam in calcul la modul general.

**Comment by ClaudiuCeia** [comment]
cc @rusanu, maestrul bazelor de date, ca sa hotaram daca inchidem issue-ul aici sau schimbam ceva ca e deja deschis de o saptamana :)

**Comment by rusanu** [comment]
Sincer eu am vazut acest guide (specific, cel de CamelCase) ca un guideline *pentru proiectele care au decis sa urmeze CamelCase*. Nu-l vad in nici un caz ca un guideline pentru *orice* database project, pentru ca numeroase medii de dezvoltare se dezvolta mult mai natural in alte conventii (eg. rails vrea `under_score` out-of-the-box). 

Deci intrebarea cheie este: acest ghid, ajuta?  Daca I-l citesti asa cum l-am interpretat eu (adica un ghid *pentru proiectele care au decis sa adopte CamelCase) atunci da, dar as pastra doar citeva points:
 
 - pluralize table names
 - TableId vs. IdTable vs. Id
 - UserFiles vs. UsersFiles (desi asta e discutabil daca e one:many vs. many:many)
 - singular column names vs. pluralized complex columns
 
Si ar trebuii rescris in Romana.

**Comment by mess110** [comment]
Use best practices according to the technology.

Cand am vazut CamelCase obligatoriu, nu am mai citit.

**Comment by rusanu** [comment]
Sters
