### ISSUE TITLE
Limba folosită pentru interfața cu utilizatorul 

### ISSUE THREAD

**Issue by timotei** [gov-ithub/guidelines#19]
Ar fi bine să se stabilească/discute direcția în care vrem să mergem: suportăm doar limba română, sau avem în vedere l10n? Poate merită stabilit un guideline la nivel global sau în funcție de proiect.

Iar pt limba română probabil ar fi util să se specifice folosirea diacriticelor?

**Comment by cezarneaga** [comment]
my 2c: eu as vrea sa avem in vedere support pt I10n. e frumos cand esti strain in alta tara si siturile pe care ai treaba au support pt engleza. In plus de asta avem si 1.4M maghiari in Romania. 
ca si guideline eu sunt pentru a avea un paragraf despre asta. la fel cum e nevoie si de unu pentru accessibilitatea frontendului.
