### ISSUE TITLE
grupare proiecte

### ISSUE THREAD

**Issue by nicolaetusinean** [gov-ithub/guidelines#2]
De ce au fost grupate cele mai multe proiecte intr-un singur repository - hackaton-v0.0.1 ? Nu se mai lucreaza la ele? Raman doar prietenul-pacientului, romanescu si infotranspub?

**Comment by cezarneaga** [comment]
Salut @nicolaetusinean!
Proiectele nu au fost abandonate. Repornesc intr-un mod structurat cu specificatii. Cand incepem sa scriem cod o sa publicam repos. Hackatonul a avut rolul de a porni echipele si sa stii ca toate proiectele sunt active. Daca nu esti pe slack, hai acolo si intra in canalele echipelor.

**Comment by rusanu** [comment]
Pentru intrebari, folosim Slack. Inchid issue pentru ca nu este actionabil la acest repo.
