### ISSUE TITLE
Creating a pull request template for repositories

### ISSUE THREAD

**Issue by cezarneaga** [gov-ithub/guidelines#9]
https://help.github.com/articles/creating-a-pull-request-template-for-your-repository/

similar cu issue template de mai sus

**Comment by ClaudiuCeia** [comment]
Nice one, nu stiam ca exista

**Comment by rusanu** [comment]
Closing as not actionable issue. Git issues is not a good discussion env.

**Comment by cezarneaga** [comment]
eu l-am pus acolo in speranta ca cineva din comunitate face pull request pe el si creaza acest fisier

**Comment by ClaudiuCeia** [comment]
Pff, trebuie sa-mi fac curat la mail-uri, asta mi-a venit in tab-ul de
"Forum" la gmail (accept tips and tricks)

Claudiu

**Comment by ClaudiuCeia** [comment]
Done.
